### ISSUE TITLE
Collections only have one item per row on JF 10.11.X

### ISSUE THREAD

**Issue by ToTheXtreme64** [lscambo13/ElegantFin#144]
Describe the bug
In collections the items only show one per row

Expected behavior
The items should be able to fit a bunch in a row

Screenshots
<img width="1374" height="1295" alt="Image" src="https://github.com/user-attachments/assets/9c4457f6-a033-486a-a8a6-fb3fe5a0a791" />
<img width="1373" height="1304" alt="Image" src="https://github.com/user-attachments/assets/4af06ba0-c84d-479c-a03a-4faca4931fe2" />

ElegantFin:

    Version [25.10.27]

Jellyfin Server:

    Version [10.11.1]

Desktop (please complete the following information):

    OS: [Windows]
    Browser: [Firefox]
    Browser Version: [144.0]
    Screen Resolution [any resolution]

Smartphone or TV (please complete the following information):

    Device: [iPhone 17 Pro]
    OS: [IOS 26.1]
    Browser: [Jellyfin app]
    Jellyfin App Version: 1.7.0

**Comment by Giggitybyte** [comment]
I don't have this issue. ElegantFin v25.10.27, Jellyfin 10.10.7.
<img width="1920" height="950" alt="Image" src="https://github.com/user-attachments/assets/2b31a7d8-21ea-4bdb-b595-603a26cbce9f" />

**Comment by trollollol123** [comment]
I also have this issue with one row latest jellyfin docker server. (10.11.1)

**Comment by lscambo13** [comment]
This has been fixed and will be released in a future update. Stay tuned.

**Comment by didi3r11** [comment]
At 10.11.2 I still have problem with Seasons.
They are not in the middle.

<img width="1884" height="812" alt="Image" src="https://github.com/user-attachments/assets/47aa555d-4b93-4ac5-8f7a-5eedc7eea1b7" />

**Comment by Spoderman708** [comment]
I managed to temporarily solve this by adding custom CSS code under the theme (works in mobile view):

> @import url("https://cdn.jsdelivr.net/gh/lscambo13/ElegantFin@main/Theme/ElegantFin-jellyfin-theme-build-latest-minified.css");
> 
> #itemDetailPage .detailSection {
>   grid-template-columns: none !important;
> }
> 
> #itemDetailPage h2.sectionTitle.sectionTitle-cards {
>   margin-bottom: 10px !important;
> }

<img width="1913" height="865" alt="Image" src="https://github.com/user-attachments/assets/0a042983-f060-4acc-93fb-1ac8ac3bb5ce" />

**Comment by Pukimaa** [comment]
A temporary fix that I use:
```css
.detailSection:has(.collectionItems:not(.hide)) {
    grid-template-columns: none !important;
}

.collectionItems > div > div {
    padding-left: 0 !important;
}
```

This will make sure it only applies to collections.
