### ISSUE TITLE
[Bug][Windows] Items in homepage don't have horizontal spacing

### ISSUE THREAD

**Issue by p-monteiro** [lscambo13/ElegantFin#3]
![image](https://github.com/user-attachments/assets/07feba29-aa17-4dfa-800c-1076581d28ee)

Tested on Jellyfin Media Player 1.11.1 (Windows)

**Comment by lscambo13** [comment]
This is an issue with JMP as it may be using an outdated web engine internally.

Regardless, it has been addressed in the latest version (v24.12.03). 

You may need to hard refresh the page to make sure that the latest theme is pulled. To make sure that you are using the latest version of ElegantFin, check the version number at the bottom in the Dashboard screen.

Please check and report.

44ed2bae27419895df07bc017d3a6ad8ba9713f8

**Comment by p-monteiro** [comment]
Thanks, but still not fixed. 
Dashboard on web says 24.12.03 (Dashboard on application says nothing).

**Comment by p-monteiro** [comment]
You are right, I could not refresh the cache from within the app as much as I tried. Had to remove the cache folder. 
Seems fixed now.
