### ISSUE TITLE
Symbols instead of icons on LG WebOS

### ISSUE THREAD

**Issue by AlessandroTischer** [lscambo13/ElegantFin#39]
**Describe the bug**
On WebOS most of the icons are replaced with ideograms or other symbols

**Expected behavior**
Icons displayed just like on any other client

**Screenshots**
![IMG_20250121_124747.jpg](https://github.com/user-attachments/assets/d600e793-ed76-4bd0-9bcb-cf1c2f217bde)

![IMG_20250121_124639.jpg](https://github.com/user-attachments/assets/01529cd1-b931-433e-90f6-d403d90a0b1f)

![IMG_20250121_124634.jpg](https://github.com/user-attachments/assets/3986f51d-f8ef-465e-aa91-784e1a2e9405)

**ElegantFin:**
 - Version [latest nightly]

**Smartphone or TV (please complete the following information):**
 - Device: [LG TV]
 - OS: [WebOS 4]
 - Browser [WebOS Jellyfin App]

**Comment by AlessandroTischer** [comment]
> This is weird, but it seems like [an issue with WebOS or PiHole](https://www.reddit.com/r/youtubetv/comments/e27go3/chinese_symbols_instead_of_icons_on_lg_tv/).
> 
> Otherwise, could you please show me how these icons look without ElegantFin? 

Without elegantfin the interface is perfectly normal:

![Image](https://github.com/user-attachments/assets/36e03981-7788-41d7-ad83-d7bd4beb2bdf)

>Can you also test the development version and post a screenshot here for comparison?. You'll have to copy-paste the entire code from [here](https://raw.githubusercontent.com/lscambo13/ElegantFin/refs/heads/main/Theme/ElegantFin-theme-nightly.css).

I would say it's the same as the nightly:

![Image](https://github.com/user-attachments/assets/3e33b195-48c5-4c19-a285-b0d234520a9f)

**Comment by lscambo13** [comment]
I'll try to find a solution without changing back to the original icons, but I can't test on WebOS myself since I don't have an LG TV.

Also, try various suggestions mentioned in https://www.reddit.com/r/youtubetv/comments/e27go3/chinese_symbols_instead_of_icons_on_lg_tv/ and let me know.

**Comment by Brumanuel** [comment]
Same problem with WebOS 3.5

**Comment by AlessandroTischer** [comment]
> [@AlessandroTischer](https://github.com/AlessandroTischer) and [@Brumanuel](https://github.com/Brumanuel) do you still have this issue?
> 
> If yes, can you test out the nightly version?
> 
> STEPS:
> 
> 1. Copy entire code from [here](https://raw.githubusercontent.com/lscambo13/ElegantFin/refs/heads/main/Theme/ElegantFin-theme-nightly.css)
> 2. Change    `--iconPack: 'Material Icons Round';` to     `--iconPack: 'Material Icons';`
> 3. Paste into into the Custom CSS box
> 4. Restart your apps and webpages
> 
> ![Image](https://github.com/user-attachments/assets/2244165f-3ae8-4598-ace2-fba13ccccd4a)

This seems to have solved the problem! Thank you!!!

**Comment by lscambo13** [comment]
I've released a stable update, so you can switch back to it to continue receiving automatic updates.

To avoid the hassle of editing the theme manually after each update, simply add the following code at the end in Custom CSS box:

```
:root{
  --iconPack: 'Material Icons';
}
```

This will ensure that you have the latest stable version of the theme with icon pack override.

**Comment by AlessandroTischer** [comment]
> I've released a stable update, so you can switch back to it to continue receiving automatic updates.
> 
> To avoid the hassle of editing the theme manually after each update, simply add the following code at the end in Custom CSS box:
> 
> ```
> :root{
>   --iconPack: 'Material Icons';
> }
> ```
> 
> This will ensure that you have the latest stable version of the theme with icon pack override.

Thank you very much!

**Comment by cmd51247** [comment]
> I've released a stable update, so you can switch back to it to continue receiving automatic updates.
> 
> To avoid the hassle of editing the theme manually after each update, simply add the following code at the end in Custom CSS box:
> 
> ```
> :root{
>   --iconPack: 'Material Icons';
> }
> ```
> 
> This will ensure that you have the latest stable version of the theme with icon pack override.

This doesn't seem to be working with the latest 10.11.3, it's still showing images/clicking on them results in no action.
