### ISSUE TITLE
Media cards have gotten significantly smaller on desktop in latest update

### ISSUE THREAD

**Issue by stephanrenggli** [lscambo13/ElegantFin#72]
**Describe the bug**
With the latest update the media cards have gotten significantly smaller on desktop. To me they now feel too small on a relatively high resolution (2k) screen.

**Expected behavior**
Media cards are still the same size as before the update.

**Screenshots**

**ElegantFin:**
 - Version [v25.08.02](https://github.com/lscambo13/ElegantFin/releases/tag/v25.08.02)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 138.0.7204.184
 - Screen Resolution 2560x1440

**Additional context**
I really like the latest update but the cards are now too small for my taste. Is this intended and is there an option to scale them up to the same size they were before the update?

**Comment by lscambo13** [comment]
I too have a 1440p and cards have been made smaller in the update, but they shouldn't be too small. Please share some screenshots so that I get a better idea of your issue.

All the new screenshots I posted in the README.md file are taken on this resolution with 125% zoom level.

Actually, in the new update, cards size is more dynamic based on the screen resolution, so on bigger screens, more icons are visible. Previously, cards were fixed in size, so although the font got much smaller, the cards did not. That made the interface look imbalanced. Now card sizes scale in proportion to the font size better.

You can zoom in using `Ctrl`+`Plus`. Let me know if zooming in fixes this issue. 

If it still doesn't help, just share some screenshots for reference and I'll address this.

**Comment by stephanrenggli** [comment]
When zooming to 110-125% the cards are about the same size as before.

I think using zoom is okay, but if there was an easy way to change this in CSS I would probably still prefer that. Not a big issue though.

**Comment by d4rk-4lchemy** [comment]
I'm using 4k screen, with 150% scaling in Windows and cards are WAY smaller. But only on web browser (Firefox 141.0), Jellyfin Windows App is still showing what it used to show and what I treat as a correct version.
**Jellyfin Media Player (Windows)**

<img width="3840" height="2066" alt="Image" src="https://github.com/user-attachments/assets/51cb006d-f498-4c73-a50a-f0b6ef763db8" />

**Firefox (141.0), no zoom**

<img width="3829" height="1942" alt="Image" src="https://github.com/user-attachments/assets/e8ce21f8-29b7-497a-a2fb-a1dc09f6712e" />

The same look as JMP can only be achieved after zooming 140% in web browser. And I don't think using zoom should be the default option.

**Comment by lscambo13** [comment]
> Jellyfin Windows App is still showing what it used to show and what I treat as a correct version.

It is not just the cards, if you look closely at the buttons and other tabs, you can notice that JMP is automatically zooming in the page. However, Firefox is not doing it automatically for some reason which means users have to zoom in manually.

Regardless, I will test more once I get enough time and I'll see what I can do.

**Comment by lscambo13** [comment]
> I think using zoom is okay, but if there was an easy way to change this in CSS I would probably still prefer that. Not a big issue though.

You can try changing it in CSS until I tweak it. 

Look for `--cardCount` and lower it to get bigger cards or increase it to get smaller cards.

Try it and let me know which number looks good at 100% scale.

**Comment by lscambo13** [comment]
@stephanrenggli and @d4rk-4lchemy 

This should be fixed in the nightly. Could you test?

```
@import url("https://cdn.jsdelivr.net/gh/lscambo13/ElegantFin@main/Theme/ElegantFin-theme-nightly.css");
```

**Comment by d4rk-4lchemy** [comment]
@lscambo13 thanks!
Still too small for my liking, but now I can see the idea behind it. Probably I'm just more used to the old one than against the new one :)

Screenshot from Firefox, no zoom:
<img width="3836" height="1936" alt="Image" src="https://github.com/user-attachments/assets/a0dfe76c-875b-43c7-bfb5-b1b8777139cf" />

**Comment by Gauvino** [comment]
Here i have the same problem, on an odyssey oled G9 4K Monitor, look at the size of the cards:

<img width="5120" height="1271" alt="Image" src="https://github.com/user-attachments/assets/c75d58b8-c86e-4559-a211-0332ac9db9b9" />

**Comment by lscambo13** [comment]
> Here i have the same problem, on an odyssey oled G9 4K Monitor

This is addressed in the nightly. How does it look there? Let me know.

```
@import url("https://cdn.jsdelivr.net/gh/lscambo13/ElegantFin@main/Theme/ElegantFin-theme-nightly.css");
```

**Comment by Gauvino** [comment]
reset cache and everything but still the same problem i think

**Comment by lscambo13** [comment]
> reset cache and everything but still the same problem i think

It should not be the same. Are you sure you have the nightly version? 

What version does it show in the Dashboard?

**Comment by Gauvino** [comment]
<img width="273" height="107" alt="Image" src="https://github.com/user-attachments/assets/5e542219-52b7-47fe-99ee-21aef125f016" />

Here im on nightly but it doesn't seem to be fix.
Maybe i missed something on how to clear the cache

**Comment by lscambo13** [comment]
> Here im on nightly but it doesn't seem to be fix.

Card sizes will not return to the size they were before, but they will be larger than in v25.08.02.

> <img width="5120" height="1271" alt="Image" src="https://github.com/user-attachments/assets/1fe1527b-e562-4d64-ba1f-21d4515a2cd5" />

How do they compare with this? Please post another screenshot with the nightly.

**Comment by Gauvino** [comment]
ok so it's approximately the same as not nightly, I think then you need to change the card size of media at the top and continue to watch to be more large because compared to the size of movies or else it's really tiny

**Comment by lscambo13** [comment]
An update to increase card sizes has been released. They still won't become oversized like before, but it should be a noticeable improvement.
